import crypto from 'node:crypto'
import { execute, query } from './db.js'

const DEFAULT_ADMIN_EMAIL = 'admin@pastisseria.local'
const DEFAULT_ADMIN_PASSWORD = 'cambia-esta-clave'
const DEFAULT_ADMIN_NAME = 'Administrador'
const SESSION_TTL_HOURS = Number(process.env.ADMIN_SESSION_TTL_HOURS ?? 12)

function createHttpError(message, statusCode) {
  const error = new Error(message)
  error.statusCode = statusCode
  return error
}

function createPasswordHash(password) {
  const salt = crypto.randomBytes(16).toString('hex')
  const hash = crypto.scryptSync(password, salt, 64).toString('hex')
  return `${salt}:${hash}`
}

function verifyPassword(password, storedHash) {
  const [salt, hash] = `${storedHash ?? ''}`.split(':')

  if (!salt || !hash) {
    return false
  }

  const derivedHash = crypto.scryptSync(password, salt, 64)
  const storedHashBuffer = Buffer.from(hash, 'hex')

  if (derivedHash.length !== storedHashBuffer.length) {
    return false
  }

  return crypto.timingSafeEqual(derivedHash, storedHashBuffer)
}

function hashToken(token) {
  return crypto.createHash('sha256').update(token).digest('hex')
}

function createSessionExpiryDate() {
  return new Date(Date.now() + SESSION_TTL_HOURS * 60 * 60 * 1000)
}

function sanitizeAdminUser(adminUser) {
  return {
    id: adminUser.id,
    name: adminUser.name,
    email: adminUser.email,
  }
}

export async function ensureAdminAuthSchema() {
  await execute(`CREATE TABLE IF NOT EXISTS admin_users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
  )`)

  await execute(`CREATE TABLE IF NOT EXISTS admin_sessions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_user_id INTEGER NOT NULL REFERENCES admin_users(id) ON DELETE CASCADE,
    token_hash VARCHAR(64) NOT NULL UNIQUE,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
  )`)

  await execute(
    `CREATE INDEX IF NOT EXISTS admin_sessions_expires_at_idx
     ON admin_sessions (expires_at)`,
  )
}

export async function ensureDefaultAdminUser() {
  const email = `${process.env.ADMIN_EMAIL ?? DEFAULT_ADMIN_EMAIL}`.trim().toLowerCase()
  const password = `${process.env.ADMIN_PASSWORD ?? DEFAULT_ADMIN_PASSWORD}`.trim()
  const name = `${process.env.ADMIN_NAME ?? DEFAULT_ADMIN_NAME}`.trim()
  const [{ total }] = await query(
    'SELECT COUNT(*)::int AS total FROM admin_users WHERE active = TRUE',
  )

  if (total > 0 && !process.env.ADMIN_PASSWORD && !process.env.ADMIN_EMAIL) {
    return
  }

  await execute(
    `INSERT INTO admin_users (name, email, password_hash)
     VALUES (:name, :email, :passwordHash)
     ON CONFLICT (email)
     DO UPDATE SET
       name = EXCLUDED.name,
       password_hash = EXCLUDED.password_hash,
       active = TRUE,
       updated_at = CURRENT_TIMESTAMP`,
    {
      name,
      email,
      passwordHash: createPasswordHash(password),
    },
  )

  if (!process.env.ADMIN_PASSWORD && total === 0) {
    console.warn(
      `No se definio ADMIN_PASSWORD. Se creo el usuario ${email} con una clave temporal que debes cambiar antes de exponer la app.`,
    )
  }
}

export async function ensureAdminAccess() {
  await ensureAdminAuthSchema()
  await ensureDefaultAdminUser()
}

export function getAdminSessionToken(request) {
  const authorization = request.headers.authorization ?? ''

  if (authorization.startsWith('Bearer ')) {
    return authorization.slice('Bearer '.length).trim()
  }

  return `${request.query.access_token ?? ''}`.trim()
}

export async function loginAdminUser({ email, password }) {
  const normalizedEmail = `${email ?? ''}`.trim().toLowerCase()
  const normalizedPassword = `${password ?? ''}`

  const [adminUser] = await query(
    `SELECT id, name, email, password_hash AS "passwordHash", active
     FROM admin_users
     WHERE email = :email
     LIMIT 1`,
    { email: normalizedEmail },
  )

  if (!adminUser?.active || !verifyPassword(normalizedPassword, adminUser.passwordHash)) {
    throw createHttpError('Credenciales no validas.', 401)
  }

  await execute('DELETE FROM admin_sessions WHERE expires_at <= CURRENT_TIMESTAMP')

  const token = crypto.randomBytes(32).toString('base64url')
  const expiresAt = createSessionExpiryDate()

  await execute(
    `INSERT INTO admin_sessions (admin_user_id, token_hash, expires_at)
     VALUES (:adminUserId, :tokenHash, :expiresAt)`,
    {
      adminUserId: adminUser.id,
      tokenHash: hashToken(token),
      expiresAt,
    },
  )

  return {
    token,
    expiresAt: expiresAt.toISOString(),
    user: sanitizeAdminUser(adminUser),
  }
}

export async function getAdminUserFromToken(token) {
  const normalizedToken = `${token ?? ''}`.trim()

  if (!normalizedToken) {
    return null
  }

  const [session] = await query(
    `SELECT
       s.id,
       s.expires_at AS "expiresAt",
       u.id AS "userId",
       u.name,
       u.email,
       u.active
     FROM admin_sessions s
     INNER JOIN admin_users u ON u.id = s.admin_user_id
     WHERE s.token_hash = :tokenHash
       AND s.expires_at > CURRENT_TIMESTAMP
     LIMIT 1`,
    { tokenHash: hashToken(normalizedToken) },
  )

  if (!session?.active) {
    return null
  }

  return {
    token: normalizedToken,
    expiresAt: session.expiresAt,
    user: {
      id: session.userId,
      name: session.name,
      email: session.email,
    },
  }
}

export async function logoutAdminUser(token) {
  const normalizedToken = `${token ?? ''}`.trim()

  if (!normalizedToken) {
    return
  }

  await execute('DELETE FROM admin_sessions WHERE token_hash = :tokenHash', {
    tokenHash: hashToken(normalizedToken),
  })
}

export async function requireAdminAuth(request, response, next) {
  try {
    const token = getAdminSessionToken(request)

    if (!token) {
      throw createHttpError('Debes iniciar sesion para continuar.', 401)
    }

    const session = await getAdminUserFromToken(token)

    if (!session) {
      throw createHttpError('La sesion no es valida o ha caducado.', 401)
    }

    request.adminSession = session
    next()
  } catch (error) {
    next(error)
  }
}
